[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm install --legacy-peer-deps --force --prefix frontend"]

[phases.build]
cmds = ["npm run build --prefix frontend"]

[start]
cmd = "cd frontend && npx serve -s build -p $PORT"

[variables]
NODE_ENV = "production"