[variables]
NODE_ENV = "production"
CORS_ORIGIN="http://localhost:3000"

[phases.setup]
nixPkgs = ["nodejs-22_x", "npm-9_x"]

[phases.install] 
cmds = ["cd backend && npm install --production"]

[phases.migrate]
cmds = ["cd backend && npm run migrate"]

[start]
cmd = "cd backend && npm start"